# Create Array 

In [1]:
import numpy as np

In [2]:
# create from python list
list_1 = [1, 2, 3, 4]

In [3]:
list_1

[1, 2, 3, 4]

In [4]:
array_1 = np.array(list_1)

In [5]:
array_1

array([1, 2, 3, 4])

In [6]:
list_2 = [5, 6, 7, 8]

In [7]:
array_2 = np.array([list_1, list_2])

In [8]:
array_2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
array_2.shape

(2, 4)

In [10]:
array_2.size

8

In [12]:
array_2.dtype

dtype('int32')

In [13]:
array_3 = np.array([[1.0, 2, 3],[4.0, 5, 6]])

In [14]:
array_3.dtype

dtype('float64')

In [17]:
array_4 = np.arange(1, 10, 2)

In [18]:
array_4

array([1, 3, 5, 7, 9])

In [19]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [20]:
np.zeros([2, 3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.eye(5) #Unit Matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
np.eye(5).dtype

dtype('float64')

In [24]:
a = np.arange(1,10)

In [25]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
a[1]

2

In [27]:
a[1:5]

array([2, 3, 4, 5])

In [29]:
b = np.array([[1,2,3],[4,5,6]])

In [30]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
b[1][0]

4

In [32]:
b[1, 0]

4

In [35]:
c = np.array([[1, 2, 3],[4,5,6],[7,8,9]])

In [36]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
c[:2,1:]

array([[2, 3],
       [5, 6]])

# Array and Metrix Calculation

## create an array

In [37]:
np.random.randn(10)

array([-0.78615153, -1.18019315,  0.21804074, -0.49889531,  0.35767474,
       -0.56678789, -0.33037332,  1.2809946 ,  0.3637409 ,  0.18116519])

In [39]:
np.random.randint(10, size = (2, 3))

array([[1, 4, 1],
       [7, 7, 3]])

In [42]:
np.random.randint(10, size = 20).reshape(4,5)

array([[9, 7, 4, 0, 8],
       [1, 5, 1, 3, 2],
       [6, 9, 7, 7, 8],
       [4, 9, 7, 5, 1]])

# Array Calculation

In [46]:
a = np.random.randint(10, size = 20).reshape(4,5)

In [47]:
a

array([[6, 5, 7, 5, 7],
       [8, 1, 3, 5, 0],
       [6, 5, 0, 9, 1],
       [5, 7, 2, 3, 6]])

In [48]:
b = np.random.randint(10, size = 20).reshape(4,5)

In [49]:
b

array([[9, 3, 5, 3, 1],
       [2, 0, 3, 6, 1],
       [9, 2, 5, 0, 0],
       [9, 8, 5, 9, 7]])

In [50]:
a + b

array([[15,  8, 12,  8,  8],
       [10,  1,  6, 11,  1],
       [15,  7,  5,  9,  1],
       [14, 15,  7, 12, 13]])

In [51]:
a - b

array([[-3,  2,  2,  2,  6],
       [ 6,  1,  0, -1, -1],
       [-3,  3, -5,  9,  1],
       [-4, -1, -3, -6, -1]])

In [52]:
a * b 

array([[54, 15, 35, 15,  7],
       [16,  0,  9, 30,  0],
       [54, 10,  0,  0,  0],
       [45, 56, 10, 27, 42]])

In [53]:
a / b

C:\Users\stell\Miniconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[0.66666667, 1.66666667, 1.4       , 1.66666667, 7.        ],
       [4.        ,        inf, 1.        , 0.83333333, 0.        ],
       [0.66666667, 2.5       , 0.        ,        inf,        inf],
       [0.55555556, 0.875     , 0.4       , 0.33333333, 0.85714286]])

In [54]:
np.mat([[1,2,3],[4,5,6]])

matrix([[1, 2, 3],
        [4, 5, 6]])

In [55]:
a

array([[6, 5, 7, 5, 7],
       [8, 1, 3, 5, 0],
       [6, 5, 0, 9, 1],
       [5, 7, 2, 3, 6]])

In [56]:
np.mat(a)

matrix([[6, 5, 7, 5, 7],
        [8, 1, 3, 5, 0],
        [6, 5, 0, 9, 1],
        [5, 7, 2, 3, 6]])

# Matrix Calculation

In [59]:
A = np.mat(a)

In [61]:
A

matrix([[6, 5, 7, 5, 7],
        [8, 1, 3, 5, 0],
        [6, 5, 0, 9, 1],
        [5, 7, 2, 3, 6]])

In [62]:
B = np.mat(b)

In [63]:
B

matrix([[9, 3, 5, 3, 1],
        [2, 0, 3, 6, 1],
        [9, 2, 5, 0, 0],
        [9, 8, 5, 9, 7]])

In [64]:
A + B

matrix([[15,  8, 12,  8,  8],
        [10,  1,  6, 11,  1],
        [15,  7,  5,  9,  1],
        [14, 15,  7, 12, 13]])

In [65]:
A - B

matrix([[-3,  2,  2,  2,  6],
        [ 6,  1,  0, -1, -1],
        [-3,  3, -5,  9,  1],
        [-4, -1, -3, -6, -1]])

In [66]:
A * B # For matrix, the line# should be equal to the column#

ValueError: shapes (4,5) and (4,5) not aligned: 5 (dim 1) != 4 (dim 0)

In [68]:
a = np.random.randint(10, size = 20).reshape(4,5)
b = np.random.randint(10, size = 20).reshape(5,4)

In [69]:
A1 = np.mat(a)
B1 = np.mat(b)

In [70]:
A1

matrix([[2, 0, 4, 0, 8],
        [2, 1, 3, 0, 7],
        [3, 4, 1, 3, 9],
        [2, 8, 0, 9, 8]])

In [71]:
B1

matrix([[9, 0, 4, 4],
        [2, 3, 4, 3],
        [6, 9, 9, 2],
        [3, 1, 8, 2],
        [7, 2, 4, 0]])

In [72]:
A1 * B1

matrix([[ 98,  52,  76,  16],
        [ 87,  44,  67,  17],
        [113,  42,  97,  32],
        [117,  49, 144,  50]])

# Array Common Function

In [74]:
a = np.random.randint(10, size = 20).reshape(4,5)

In [77]:
np.unique(a)  #all the unique elements in array a

array([0, 2, 3, 4, 6, 7, 8, 9])

In [78]:
a

array([[3, 0, 8, 6, 2],
       [9, 0, 0, 0, 6],
       [8, 6, 3, 3, 9],
       [9, 4, 0, 4, 7]])

In [79]:
sum(a) #sum up by column

array([29, 10, 11, 13, 24])

In [80]:
sum(a[0]) #sum up by line

19

In [81]:
sum(a[:, 0]) #sum up by one column

29

In [82]:
a.max()

9

In [83]:
max(a[0])

8

In [84]:
max(a[:, 0])

9

# Array Input and Output

## Use pickle to serialize a numpy array

In [98]:
import pickle
import numpy as np

In [99]:
x = np.arange(10)

In [100]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
f = open('x.pkl', 'wb')

In [102]:
pickle.dump(x, f)

In [104]:
f = open('x.pkl', 'rb')

In [105]:
pickle.load(f)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [106]:
np.save('one_array', x)

In [108]:
np.load('one_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [109]:
y = np.arange(20)

In [110]:
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [111]:
np.savez('two_array.npz', a=x, b=y)

In [112]:
ls

 Volume in drive C is OS
 Volume Serial Number is 5ECB-C6A3

 Directory of C:\Users\stell

01/28/2020  08:57 PM    <DIR>          .
01/28/2020  08:57 PM    <DIR>          ..
11/30/2018  01:01 AM    <DIR>          .3T
12/22/2018  12:25 PM    <DIR>          .anaconda
06/02/2019  11:56 PM    <DIR>          .android
01/15/2020  01:55 AM               134 .bash_history
11/08/2018  02:58 PM    <DIR>          .cache
08/28/2018  09:52 PM    <DIR>          .cisco
03/29/2019  10:46 PM    <DIR>          .conda
04/06/2019  04:40 PM                43 .condarc
08/30/2018  12:32 PM    <DIR>          .dbeaver4
09/06/2018  12:48 PM    <DIR>          .dbeaver-drivers
11/30/2018  01:14 PM                 0 .dbshell
12/12/2018  02:11 PM    <DIR>          .eclipse
12/05/2019  10:05 PM               200 .gitconfig
12/04/2019  11:35 PM    <DIR>          .IdeaIC2019.3
09/21/2018  11:42 PM    <DIR>          .idlerc
01/28/2020  08:16 PM    <DIR>          .ipynb_checkpoints
12/22/2018  12:47 PM    <DIR>         

In [113]:
c = np.load('two_array.npz')

In [115]:
c['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [116]:
c['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])