In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
arr1 = np.arange(9).reshape(3,3)

In [3]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
arr2 = np.arange(9).reshape(3,3)

In [5]:
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
np.concatenate([arr1,arr2])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
np.concatenate([arr1,arr2],axis = 1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [9]:
s1 = Series([1,2,3],index=['X','Y','Z'])

In [10]:
s2 = Series([4,5],index=['A','B'])

In [11]:
s1

X    1
Y    2
Z    3
dtype: int64

In [12]:
s2

A    4
B    5
dtype: int64

In [13]:
pd.concat([s1,s2])

X    1
Y    2
Z    3
A    4
B    5
dtype: int64

In [14]:
pd.concat([s1,s2],axis=1)

C:\Users\stell\Miniconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


0    1
A  NaN  4.0
B  NaN  5.0
X  1.0  NaN
Y  2.0  NaN
Z  3.0  NaN

In [16]:
df1 = DataFrame(np.random.randn(4,3),columns= ['X','Y','Z'])

In [18]:
df1

X         Y         Z
0  0.297491 -0.238039  0.897381
1  1.014681 -1.471891 -0.563179
2  0.423049  0.983347 -0.105384
3  0.222346  0.794409  0.367254

In [19]:
df2 = DataFrame(np.random.randn(3,3),columns=['X','Y','A'])

In [20]:
df2

X         Y         A
0  0.647814 -1.668802 -0.630480
1 -1.135931  1.015815  0.678719
2  0.857698  0.593402  0.091374

In [22]:
pd.concat([df1,df2])

C:\Users\stell\Miniconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


A         X         Y         Z
0       NaN  0.297491 -0.238039  0.897381
1       NaN  1.014681 -1.471891 -0.563179
2       NaN  0.423049  0.983347 -0.105384
3       NaN  0.222346  0.794409  0.367254
0 -0.630480  0.647814 -1.668802       NaN
1  0.678719 -1.135931  1.015815       NaN
2  0.091374  0.857698  0.593402       NaN

## Combine 

In [24]:
s11 = Series([2,np.nan,4,np.nan],index=['A','B','C','D'])

In [25]:
s11

A    2.0
B    NaN
C    4.0
D    NaN
dtype: float64

In [26]:
s12 = Series([1,2,3,4], index=['A','B','C','D'])

In [28]:
s12

A    1
B    2
C    3
D    4
dtype: int64

In [30]:
s11.combine_first(s12)

A    2.0
B    2.0
C    4.0
D    4.0
dtype: float64

In [31]:
df1 = DataFrame({
    'X':[1,np.nan, 3, np.nan],
    'Y':[5,np.nan, 7, np.nan],
    'Z':[9,np.nan, 11,np.nan]})

In [32]:
df1

X    Y     Z
0  1.0  5.0   9.0
1  NaN  NaN   NaN
2  3.0  7.0  11.0
3  NaN  NaN   NaN

In [33]:
df2 = DataFrame({
    'Z':[np.nan, 10, np.nan, 12],
    'A':[1, 2, 3, 4]
})

In [34]:
df2

Z  A
0   NaN  1
1  10.0  2
2   NaN  3
3  12.0  4

In [35]:
df1.combine_first(df2) # just combine

A    X    Y     Z
0  1.0  1.0  5.0   9.0
1  2.0  NaN  NaN  10.0
2  3.0  3.0  7.0  11.0
3  4.0  NaN  NaN  12.0